### ISSUE TITLE
Composable Factories?

### ISSUE THREAD

**Issue by CharlieIGG** [thoughtbot/fishery#18]
Is it possible to do composition for Factories in here?

Since FactoryBot is a point of reference for this project, I'm looking for something like `traits`, where I can generate variations from a "Base Factory".

**Comment by stevehanson** [comment]
@CharlieIGG thanks for starting this discussion. I've been thinking about this a bit too and wondering if we need something like `traits` or composable factories. 

We do have [`transientParams`](https://github.com/thoughtbot/fishery#params-that-dont-map-to-the-result-object-transient-params), which could be used to accomplish something like traits, though it's a little verbose:

```typescript
factories.user.build({}, { transient: { admin: true } })
```

I'm curious if you've tried using that and what problems you encountered. Any information you can share on the specific use-cases that you're trying to solve with this would be really helpful. Any thoughts on an API that you'd like would be welcome, too.

I am the primary maintainer of this library and will be a bit busy for the next several weeks, but I'd be happy to discuss potential solutions in this thread, and if we decide this is a feature we'd like to implement and determine a general direction, anyone would be welcome to pick up the work.

**Comment by CharlieIGG** [comment]
@stevehanson I'm just planning to get started really using Fishery for a project in the following weeks (project is half-paused due to... circumstances, same old, same old...), but at the top of my head I have this example. I've already declared this factory:

```typescript
import { Factory } from 'fishery';
import { IProperty } from '../shared_interfaces/domain_interfaces';
import * as faker from 'faker';

export const PropertyFactory = Factory.define<IProperty>( ( { sequence } ) => ( {
    id: sequence,
    label: faker.commerce.productAdjective(),
    description: faker.lorem.text(),
    required: false
} ) );
```

And say for some reason I know I will have tons of test cases where I know I will be working with required `properties`, but I want to avoid having to pass the extra params every single time like `factories.property.build({required: true});`, and instead I wish to call something like `factories.requiredProperty.build();`... in order to keep things DRY I would imagine something like the following declaration that would allow me to compose the new variant on top of my root `PropertyFactory`: 

```typescript
export const RequiredPropertyFactory = PropertyFactory.extend((propertyAttrs, {_sequence, _factories, _otherStuff}) => ( {
  ...propertyAttrs,
  required: true
})
```

This is just the first thing that occurs to me, but:
1) I'm certain there is probably a better, more elegant implementation of the core idea, and
2) I haven't really taken the time to dig deep into Fishery's code to understand the implications, but the general idea is that we could just get the O.G. properties that we would get from the original Factory as the first (object) argument in the "extended"/"composed" factory declaration – which we can merge with the new object declaration using object destructuring – and an object with the common props that Fishery already passes to help dynamically construct the new object, such as `sequence`, and `factories`. 

Does this make any sense to you?

**Comment by CharlieIGG** [comment]
I made a fork intending to do a PR with a PoC, but I've been running around in circles hoping to come up with an idea on how to start implementing this, without much success 🤔

**Comment by stevehanson** [comment]
Thank you for sharing all this, @CharlieIGG! It's helpful to see your use-cases. I've run into similar issues and have found myself occasionally making helper functions like `buildRequiredProperty` that then call the factories. I'd like to find a way to not have to do that. At first glance, I like the idea of being able to extend factories. This is like factory_bot's nested factories. 

Another thought I had would be to come up with an API for something more like traits. A benefit of traits is that you can combine multiple. Here's an API that could be convenient, though I am not sure how feasible it would be with the way types are currently set up (all factories are expected to have the same type signature):

```typescript
factories.user.admin().build()
factories.user.registered().withPosts().build()
```

It's possible that we could end up wanting both: composable factories and this traits concept. If we decide so, we can scope this conversation to just one or the other.

I unfortunately will probably not have time to look more into this in the next week or two.

**Comment by CharlieIGG** [comment]
@stevehanson your idea for the trait API looks perfectly convenient to me... I think the two concepts are complimentary in some ways... but definitely the capability of using `factories.<baseFactory>.<trait>` is 100% more convenient than having separate factories "floating around" with no obvious relationship.

I'm quite interested in contributing, but JS (and TS for that matter) are not necessarily my strong points. That being said, if you can point me in the right direction, I'm sure I can be of use to you here.

**Comment by stevehanson** [comment]
I just put together a rough implementation, and I'm pleased that this traits API seems like it will be doable. It also feels really nice and flexible to work with trait functions. Here's [what I have so far in a branch](https://github.com/thoughtbot/fishery/compare/traits?expand=1). Check out the test cases to see some of the new possibilities with the API.

### Things to think through

My main goal tonight was to just get a proof of concept, and there are still some things I'd like to think through:

#### Defining factories with traits

Since factories are basically classes, the way I implemented traits was by having the user subclass the root `Factory` class. So, the old method of defining a factory goes from:

```typescript
const userFactory = Factory.define<User>(() => ({
    id: '1',
    name: 'Bob',
    admin: false,
});

userFactory.build()
```

to:

```typescript
class UserFactory extends Factory<User> {
  // custom traits here
  admin() {
    return this.addParams({ admin: true })
  }
}

const userFactory = new UserFactory(() => ({
  id: '1',
  name: 'Bob',
  admin: false,
}));

userFactory.build()
userFactory.admin().build()
```

The main thing that bothers me about this approach is that it deviates from the existing way factories are defined. I don't mind subclassing factory to define the traits since I'm not sure if there is a way around that, but I don't like that the factory method then needs to be defined with `new UserFactory` instead of `UserFactory.define`. I wasn't able to figure out tonight how to get the static method `define` to return the subclass type. It always returns a `Factory`. Here's a [relevant Typescript issue](https://github.com/microsoft/TypeScript/issues/5863).

#### the trait methods themselves

You can see above that the trait calls a new `addParams` method. This is probably sufficient for most use-cases, but it doesn't provide a way to define custom callbacks like `afterCreate`. These features could be added later, but it's probably worth thinking about now. I could see `addParams` going away and maybe a more generic `extend` or something coming into play that we can also use more generally for factory composition.

#### the addParams method implementation

The goal of the `addParams` method was that it would immutably add params to a running list of params. These params would then get merged with the user-supplied params when `build` is called. To implement this, I added a `clone` method that bypasses some type safety. I'm sure there's a better way, so I'd like to clean that up.

**Comment by CharlieIGG** [comment]
@stevehanson I see [from this comment](https://github.com/microsoft/TypeScript/issues/5863#issuecomment-632961592) that you figured a way around the fixation of `this` inside class heirs 👍. Did this help in coming back to just using the `define` call?

I'm not 100% sure that `addParams` would scale up... I'm trying to think of an alternative... 🤔

**Comment by stevehanson** [comment]
@CharlieIGG yes, it did! 

I've done some more work on this and expect to have a PR ready soon. Hopefully this week. What I've ended up doing is creating a public API for extending factories:

```typescript
const registeredAdminFactory = userFactory
  .params({ admin: true })
  .transient({ registered: true })
  .afterCreate(() => ...)

registeredAdminFactory.build()
```

The `params`, `transient`, `afterCreate`, etc. create a new factory with the specified values set on it.

Traits, or any method defined on a factory, can also utilize this same API:

```typescript
class UserFactory extends Factory<User> {
  admin() {
    return this.params({ admin: true })
  }

  registered() {
    return this.transient({ registered: true })
  }

  withPosts(num: number, options: DeepPartial<Post> = {}) {
    return this
      .associations({ posts: postsFactory.buildList(num, options) })
      .afterCreate(user => { ... })
  }
}

// params, transient params, associations, etc, from the traits come through here as if they were passed with `build`
const userFactory = UserFactory.define(({ params, transientParams, associations ) => ({ ... })

const user = userFactory.admin().registered().withPosts(2).build()
```

I like this approach since it allows us to do two things with a single API: extend factories _and_ define traits. That keeps the surface area of things to learn with Fishery low, so it remains as easy as possible for new users to pick up.

**Comment by CharlieIGG** [comment]
@stevehanson I love your idea, it is a simple, yet awesome approach!
