### ISSUE TITLE
DeepPartial does not work with generic constraints

### ISSUE THREAD

**Issue by ChrisMancini** [thoughtbot/fishery#70]
I am having an issue with `DeepPartial` and the use of generic constraints in Typescript v4.3.5

This is a simple scenario (while this error also occurs within the Factory implementation, I simplified the scenario for brevity)

````
interface Base {
  id: number;
}

interface Child extends Base {
  value: string;
}

class Test<T extends Base> {
  log() {
    // Fails with Type '{ id: 0; }' is not assignable to type 'DeepPartial<T>'.
    const x : DeepPartial<T> = {id: 0};

    // Success
    const y: DeepPartial<Base> = {id: 0};
  }  
}

const childTest = new Test<Child>();

**Comment by stevehanson** [comment]
Hi, @ChrisMancini this seems to be an issue with TypeScript itself, not Fishery. Your example can be recreated with plain TypeScript if you change `DeepPartial` (from Fishery) to `Partial` (from TS). Here is a [TS Playground ](https://www.typescriptlang.org/play?#code/FASwdgLgpgTgZgQwMZQAQCEEGc0G9iqogAmAXKmAK4C2ARrANzAC+woksiKqAwgBYgANsVRQAHtDDEsGbHgKoAbgkGUo5LBBjgA5k1bAkg7DIAqUTQB5ToiVCkzMOAHyp8hQQHsdACgCUbgqEAPTBqABiCEIyAO4gEHyopgCeAA5oAOS4RGSoAAwMqMwZRDJgnhCoJiA6YAi0gmgQnqgQaZkAIlBQqQAKCDAQICrWzhkAdEGoSJ5gmqhiqOT9g8OCo6gAvG4k5HnMTISEYuMkbEeooagAypRIKFhYUzNzlcnLA0MjTlCu27i7fIHBTMQgsIA) showing this.

Some references to this issue: [here](https://stackoverflow.com/questions/59279796/typescript-partial-of-a-generic-type), [here](https://stackoverflow.com/questions/63553256/typescript-issues-using-partialt-on-a-bounded-generic-type), and [here](https://github.com/microsoft/TypeScript/issues/22229). Since this is a TS issue, I will go ahead and close this.

**Comment by ChrisMancini** [comment]
Thank you for the thorough explanation and research!
